### ISSUE TITLE
Missing Automation Task

### ISSUE THREAD

**Issue by Stickyhavr** [Stephen-Lon/Alfred-workflow-word-count#1]
Hello,
Just an FYI: when I first downloaded this workflow I was missing the automation task. I think that's because I have never used any automation tasks since switching to Alfred 5. Anyway, once I clicked download tasks or updates tasks (I can't remember exactly what it said), then it automatically had "Get text metrics, count: words" selected. 

So it was easy to fix but perhaps you might want to make a note or something in case anyone else has the same experience.

Also, now that you're posting stuff on GitHub, I would recommend including the link in the "About this Workflow" notes so that people will remember where they got it from and also able to quickly see if there's an update, etc.

Thanks for posting all of these. I find them quite useful and they have inspired me to dig into some of the new Alfred 5 features.

**Comment by Stephen-Lon** [comment]
Many thanks for that. I have added a warning to the Read Me here on Github and have also included it in the `Configure Workflow` details of the new version (2.1) of the workflow just uploaded. That is the only change to the workflow so there's no need to download the new version unless you want that warning!

I much appreciate the comments which, as a very new Github user, help me a lot. Thank you.

Stephen

**Comment by Stickyhavr** [comment]
Great. Thanks!
