### ISSUE TITLE
Doesn't seem to be working on Alfred 5

### ISSUE THREAD

**Issue by skymakai** [Stephen-Lon/Alfred-workflow-word-count#3]
Checked and made sure automations are up to date.  Can't seem to get it to work.

**Comment by Stephen-Lon** [comment]
Please confirm what version of macOS you are using. Please also describe exactly how you are trying to use the workflow. You should be selecting text and then using your Alfred Universal Action hotkey to call the workflow. It works perfectly for me using Alfred 5 on macOS Sonoma (as it did on Ventura).

**Comment by skymakai** [comment]
Disregard.  My Universal Hotkey wasn't set up... was trying to use the Alfred Hotkey.  Thank you.
